<?php

declare(strict_types=1);
require_once __DIR__ . '/includes/admin_auth.php';
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);
if(!$id){flash('warning','Promo tidak valid.');redirect('promotions.php');}
$stmt=$pdo->prepare('SELECT * FROM promotions WHERE id=:id');$stmt->execute(['id'=>$id]);$promotion=$stmt->fetch();
if(!$promotion){flash('warning','Promo tidak ditemukan.');redirect('promotions.php');}
$usageStmt=$pdo->prepare("SELECT pu.*,o.order_number,o.total_amount,u.name AS customer_name,u.email FROM promotion_usages pu INNER JOIN orders o ON o.id=pu.order_id INNER JOIN users u ON u.id=pu.user_id WHERE pu.promotion_id=:id ORDER BY pu.id DESC");$usageStmt->execute(['id'=>$id]);$usages=$usageStmt->fetchAll();
$summary=['used'=>0,'restored'=>0,'product'=>0.0,'shipping'=>0.0];foreach($usages as $usage){if($usage['usage_status']==='USED'){$summary['used']++;$summary['product']+=(float)$usage['discount_amount'];$summary['shipping']+=(float)$usage['shipping_discount'];}else{$summary['restored']++;}}
$rules=get_promotion_rules($pdo,(int)$id);
$pageTitle='Detail Promo';$activeMenu='promotions';require __DIR__.'/includes/admin_header.php';
?>
<div class="admin-page-head"><div><h1><?=e((string)$promotion['name'])?></h1><p><?=e(promotion_trigger_label((string)$promotion['trigger_type']))?> · <?=e(promotion_discount_type_label((string)$promotion['discount_type']))?></p></div><div class="admin-page-actions"><a class="admin-button admin-button-secondary" href="promotions.php">← Daftar Promo</a><a class="admin-button admin-button-primary" href="promotion_form.php?id=<?=(int)$id?>">Edit Promo</a></div></div>
<section class="admin-grid admin-stats"><article class="admin-stat-card"><div class="admin-stat-copy"><span>Penggunaan Aktif</span><strong><?=$summary['used']?></strong><small><?=$summary['restored']?> penggunaan dikembalikan</small></div></article><article class="admin-stat-card"><div class="admin-stat-copy"><span>Diskon Produk</span><strong><?=rupiah($summary['product'])?></strong></div></article><article class="admin-stat-card"><div class="admin-stat-copy"><span>Diskon Ongkir</span><strong><?=rupiah($summary['shipping'])?></strong></div></article><article class="admin-stat-card"><div class="admin-stat-copy"><span>Nilai Promo</span><strong><?=e(promotion_value_label($promotion))?></strong><small>Minimal <?=rupiah($promotion['minimum_purchase'])?></small></div></article></section>
<section class="admin-card" style="margin-bottom:18px"><div class="admin-card-head"><h2>Ketentuan Promo</h2><span class="admin-badge <?= (int)$promotion['is_active']===1?'status-complete':'status-neutral' ?>"><?= (int)$promotion['is_active']===1?'Aktif':'Nonaktif' ?></span></div><div class="admin-detail-grid"><div><span>Kode</span><strong><?=e((string)($promotion['code']?:'Otomatis'))?></strong></div><div><span>Periode</span><strong><?=format_datetime((string)$promotion['start_at'])?> – <?=format_datetime((string)$promotion['end_at'])?></strong></div><div><span>Kuota</span><strong><?= $promotion['total_usage_limit']===null?'Tidak dibatasi':(int)$promotion['current_usage'].' / '.(int)$promotion['total_usage_limit'] ?></strong></div><div><span>Batas per akun</span><strong><?=(int)$promotion['usage_limit_per_user']?> kali</strong></div><div><span>Produk khusus</span><strong><?=count($rules['product_ids'])?></strong></div><div><span>Kategori khusus</span><strong><?=count($rules['category_ids'])?></strong></div><div><span>Pembayaran khusus</span><strong><?=count($rules['payment_methods'])?></strong></div><div><span>Layanan khusus</span><strong><?=count($rules['shipping_service_ids'])?></strong></div></div></section>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Pesanan</th><th>Pelanggan</th><th>Diskon Produk</th><th>Diskon Ongkir</th><th>Status</th><th>Waktu</th></tr></thead><tbody><?php if($usages===[]):?><tr><td colspan="6"><div class="admin-empty"><strong>Belum digunakan</strong><p>Riwayat penggunaan promo akan muncul di sini.</p></div></td></tr><?php endif;?><?php foreach($usages as $usage):?><tr><td><a href="order_detail.php?id=<?=(int)$usage['order_id']?>"><strong><?=e((string)($usage['order_number']?:order_code((int)$usage['order_id'])))?></strong></a><br><small>Total <?=rupiah($usage['total_amount'])?></small></td><td><?=e((string)$usage['customer_name'])?><br><small><?=e((string)$usage['email'])?></small></td><td><?=rupiah($usage['discount_amount'])?></td><td><?=rupiah($usage['shipping_discount'])?></td><td><span class="admin-badge <?= $usage['usage_status']==='USED'?'status-complete':'status-neutral' ?>"><?=e((string)$usage['usage_status'])?></span></td><td><?=format_datetime((string)$usage['used_at'])?></td></tr><?php endforeach;?></tbody></table></div>
<?php require __DIR__.'/includes/admin_footer.php';?>
