<?php

declare(strict_types=1);
require_once __DIR__ . '/includes/admin_auth.php';
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'service_id',FILTER_VALIDATE_INT);$isEdit=(bool)$id;
$couriers=$pdo->query("SELECT id,courier_name FROM shipping_couriers ORDER BY courier_name")->fetchAll();
$data=['courier_id'=>(int)($_GET['courier_id']??0),'service_code'=>'','service_name'=>'','description'=>'','min_delivery_days'=>1,'max_delivery_days'=>3,'is_active'=>1];
if($isEdit){$st=$pdo->prepare('SELECT * FROM shipping_services WHERE id=:id');$st->execute(['id'=>$id]);$data=$st->fetch()?:[];if($data===[]){flash('warning','Layanan tidak ditemukan.');redirect('shipping_services.php');}}
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$data=['courier_id'=>(int)($_POST['courier_id']??0),'service_code'=>strtoupper(trim((string)($_POST['service_code']??''))),'service_name'=>trim((string)($_POST['service_name']??'')),'description'=>trim((string)($_POST['description']??'')),'min_delivery_days'=>max(0,(int)($_POST['min_delivery_days']??0)),'max_delivery_days'=>max(0,(int)($_POST['max_delivery_days']??0)),'is_active'=>isset($_POST['is_active'])?1:0];
if($data['courier_id']<=0)$errors[]='Pilih kurir.';if(!preg_match('/^[A-Z0-9_-]{1,50}$/',$data['service_code']))$errors[]='Kode layanan tidak valid.';if(strlen($data['service_name'])<2||strlen($data['service_name'])>100)$errors[]='Nama layanan harus 2–100 karakter.';if(strlen($data['description'])>255)$errors[]='Deskripsi maksimal 255 karakter.';if($data['max_delivery_days']<$data['min_delivery_days'])$errors[]='Estimasi maksimal tidak boleh lebih kecil dari estimasi minimal.';
$check=$pdo->prepare('SELECT id FROM shipping_services WHERE courier_id=:courier_id AND service_code=:code AND id<>:id');$check->execute(['courier_id'=>$data['courier_id'],'code'=>$data['service_code'],'id'=>(int)$id]);if($check->fetch())$errors[]='Kode layanan sudah digunakan pada kurir ini.';
if($errors===[]){if($isEdit){$st=$pdo->prepare('UPDATE shipping_services SET courier_id=:courier_id,service_code=:code,service_name=:name,description=:description,min_delivery_days=:min_days,max_delivery_days=:max_days,is_active=:active,updated_at=NOW() WHERE id=:id');$st->execute(['courier_id'=>$data['courier_id'],'code'=>$data['service_code'],'name'=>$data['service_name'],'description'=>$data['description']?:null,'min_days'=>$data['min_delivery_days'],'max_days'=>$data['max_delivery_days'],'active'=>$data['is_active'],'id'=>$id]);}else{$st=$pdo->prepare('INSERT INTO shipping_services(courier_id,service_code,service_name,description,min_delivery_days,max_delivery_days,is_active) VALUES(:courier_id,:code,:name,:description,:min_days,:max_days,:active)');$st->execute(['courier_id'=>$data['courier_id'],'code'=>$data['service_code'],'name'=>$data['service_name'],'description'=>$data['description']?:null,'min_days'=>$data['min_delivery_days'],'max_days'=>$data['max_delivery_days'],'active'=>$data['is_active']]);}log_admin_activity($pdo,'shipping_service_save','Menyimpan layanan '.$data['service_name']);flash('success','Layanan kurir berhasil disimpan.');redirect('shipping_services.php?courier_id='.$data['courier_id']);}}
$pageTitle=$isEdit?'Edit Layanan':'Tambah Layanan';$activeMenu='shipping';require __DIR__.'/includes/admin_header.php';
?>
<div class="admin-page-head"><div><h1><?=e($pageTitle)?></h1><p>Atur layanan dan estimasi pengiriman.</p></div><a class="admin-button admin-button-secondary" href="shipping_services.php">← Kembali</a></div><?php if($errors):?><ul class="admin-error-list"><?php foreach($errors as $er):?><li><?=e($er)?></li><?php endforeach;?></ul><?php endif;?>
<form class="admin-card admin-form-stack" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><?php if($isEdit):?><input type="hidden" name="service_id" value="<?=(int)$id?>"><?php endif;?><div class="admin-form-grid"><label class="admin-field"><span>Kurir</span><select class="admin-select" name="courier_id" required><option value="">Pilih kurir</option><?php foreach($couriers as $c):?><option value="<?=(int)$c['id']?>" <?=(int)$data['courier_id']===(int)$c['id']?'selected':''?>><?=e((string)$c['courier_name'])?></option><?php endforeach;?></select></label><label class="admin-field"><span>Kode layanan</span><input class="admin-input" name="service_code" maxlength="50" value="<?=e((string)$data['service_code'])?>" required></label><label class="admin-field"><span>Nama layanan</span><input class="admin-input" name="service_name" maxlength="100" value="<?=e((string)$data['service_name'])?>" required></label><label class="admin-field"><span>Estimasi minimum (hari)</span><input class="admin-input" type="number" min="0" name="min_delivery_days" value="<?=(int)$data['min_delivery_days']?>" required></label><label class="admin-field"><span>Estimasi maksimum (hari)</span><input class="admin-input" type="number" min="0" name="max_delivery_days" value="<?=(int)$data['max_delivery_days']?>" required></label></div><label class="admin-field"><span>Deskripsi</span><textarea class="admin-textarea" name="description" maxlength="255"><?=e((string)$data['description'])?></textarea></label><label class="admin-check"><input type="checkbox" name="is_active" <?=(int)$data['is_active']===1?'checked':''?>><span>Layanan aktif</span></label><div class="admin-form-actions"><button class="admin-button admin-button-primary" type="submit">Simpan Layanan</button></div></form>
<?php require __DIR__.'/includes/admin_footer.php';?>
