<?php

declare(strict_types=1);require_once __DIR__.'/includes/admin_auth.php';
$serviceId=(int)($_GET['service_id']??0);$search=trim((string)($_GET['q']??''));$where=['1=1'];$params=[];if($serviceId>0){$where[]='r.shipping_service_id=:service_id';$params['service_id']=$serviceId;}if($search!==''){$where[]='(r.province LIKE :q OR r.city LIKE :q OR r.district LIKE :q OR c.courier_name LIKE :q OR s.service_name LIKE :q)';$params['q']='%'.$search.'%';}
$services=$pdo->query('SELECT s.id,CONCAT(c.courier_name," - ",s.service_name) label FROM shipping_services s INNER JOIN shipping_couriers c ON c.id=s.courier_id ORDER BY c.courier_name,s.service_name')->fetchAll();
$stmt=$pdo->prepare('SELECT r.*,s.service_code,s.service_name,c.courier_name FROM shipping_rates r INNER JOIN shipping_services s ON s.id=r.shipping_service_id INNER JOIN shipping_couriers c ON c.id=s.courier_id WHERE '.implode(' AND ',$where).' ORDER BY r.province,r.city,r.district,c.courier_name');$stmt->execute($params);$rates=$stmt->fetchAll();
$pageTitle='Tarif Ongkos Kirim';$activeMenu='shipping';require __DIR__.'/includes/admin_header.php';
?>
<div class="admin-page-head"><div><h1>Tarif Ongkos Kirim</h1><p>Tarif dihitung per kilogram berdasarkan tujuan.</p></div><div class="admin-page-actions"><a class="admin-button admin-button-secondary" href="shipping.php">← Pengiriman</a><a class="admin-button admin-button-primary" href="shipping_rate_form.php">+ Tambah Tarif</a></div></div>
<div class="admin-filter-card"><form class="admin-filter-form" method="get"><label class="admin-field"><span>Pencarian</span><input class="admin-input" name="q" value="<?=e($search)?>" placeholder="Provinsi, kota, kecamatan, kurir"></label><label class="admin-field"><span>Layanan</span><select class="admin-select" name="service_id"><option value="0">Semua layanan</option><?php foreach($services as $s):?><option value="<?=(int)$s['id']?>" <?=$serviceId===(int)$s['id']?'selected':''?>><?=e((string)$s['label'])?></option><?php endforeach;?></select></label><button class="admin-button admin-button-primary" type="submit">Terapkan</button></form></div>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Tujuan</th><th>Kurir/Layanan</th><th>Kg Pertama</th><th>Kg Berikutnya</th><th>COD</th><th>COD Cek Dulu</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($rates as $r):?><tr><td><strong><?=e((string)$r['city'])?>, <?=e((string)$r['province'])?></strong><br><small><?=e((string)($r['district']?:'Semua kecamatan'))?></small></td><td><?=e((string)$r['courier_name'])?> <strong><?=e((string)$r['service_code'])?></strong><br><small><?=e((string)$r['service_name'])?></small></td><td><?=rupiah($r['first_kg_price'])?></td><td><?=rupiah($r['next_kg_price'])?></td><td><?=(int)$r['supports_cod']===1?'Ya ('.rupiah($r['cod_fee']).')':'Tidak'?></td><td><?=(int)$r['supports_cod_check']===1?'Ya':'Tidak'?></td><td><span class="admin-badge <?=(int)$r['is_active']===1?'status-complete':'status-neutral'?>"><?=(int)$r['is_active']===1?'Aktif':'Nonaktif'?></span></td><td><div class="admin-table-actions"><a class="admin-button admin-button-primary admin-button-small" href="shipping_rate_form.php?id=<?=(int)$r['id']?>">Edit</a><form method="post" action="shipping_rate_action.php"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="rate_id" value="<?=(int)$r['id']?>"><input type="hidden" name="action" value="toggle"><button class="admin-button admin-button-warning admin-button-small" type="submit" data-confirm="Ubah status tarif ini?">Toggle</button></form><form method="post" action="shipping_rate_action.php"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="rate_id" value="<?=(int)$r['id']?>"><input type="hidden" name="action" value="delete"><button class="admin-button admin-button-danger admin-button-small" type="submit" data-confirm="Hapus tarif ini?">Hapus</button></form></div></td></tr><?php endforeach;?></tbody></table></div>
<?php require __DIR__.'/includes/admin_footer.php';?>
