<?php

declare(strict_types=1);
require_once __DIR__ . '/includes/admin_auth.php';
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'rate_id',FILTER_VALIDATE_INT);$isEdit=(bool)$id;
$services=$pdo->query('SELECT s.id,s.service_code,s.service_name,c.courier_name FROM shipping_services s INNER JOIN shipping_couriers c ON c.id=s.courier_id ORDER BY c.courier_name,s.service_name')->fetchAll();
$data=['shipping_service_id'=>(int)($_GET['service_id']??0),'province'=>'','city'=>'','district'=>'','first_kg_price'=>0,'next_kg_price'=>0,'supports_cod'=>0,'supports_cod_check'=>0,'cod_fee'=>0,'is_active'=>1];
if($isEdit){$st=$pdo->prepare('SELECT * FROM shipping_rates WHERE id=:id');$st->execute(['id'=>$id]);$data=$st->fetch()?:[];if($data===[]){flash('warning','Tarif tidak ditemukan.');redirect('shipping_rates.php');}}
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$data=['shipping_service_id'=>(int)($_POST['shipping_service_id']??0),'province'=>trim((string)($_POST['province']??'')),'city'=>trim((string)($_POST['city']??'')),'district'=>trim((string)($_POST['district']??'')),'first_kg_price'=>(float)($_POST['first_kg_price']??0),'next_kg_price'=>(float)($_POST['next_kg_price']??0),'supports_cod'=>isset($_POST['supports_cod'])?1:0,'supports_cod_check'=>isset($_POST['supports_cod_check'])?1:0,'cod_fee'=>(float)($_POST['cod_fee']??0),'is_active'=>isset($_POST['is_active'])?1:0];
if($data['shipping_service_id']<=0)$errors[]='Pilih layanan pengiriman.';if(strlen($data['province'])<2||strlen($data['province'])>100)$errors[]='Provinsi harus 2–100 karakter.';if(strlen($data['city'])<2||strlen($data['city'])>100)$errors[]='Kota/kabupaten harus 2–100 karakter.';if(strlen($data['district'])>100)$errors[]='Kecamatan maksimal 100 karakter.';if($data['first_kg_price']<0||$data['next_kg_price']<0||$data['cod_fee']<0)$errors[]='Nilai tarif tidak boleh negatif.';
$duplicate=$pdo->prepare("SELECT id FROM shipping_rates WHERE shipping_service_id=:service_id AND LOWER(TRIM(province))=LOWER(TRIM(:province)) AND LOWER(TRIM(city))=LOWER(TRIM(:city)) AND COALESCE(LOWER(TRIM(district)),'')=LOWER(TRIM(:district)) AND id<>:id LIMIT 1");$duplicate->execute(['service_id'=>$data['shipping_service_id'],'province'=>$data['province'],'city'=>$data['city'],'district'=>$data['district'],'id'=>(int)$id]);if($duplicate->fetch())$errors[]='Tarif untuk layanan dan tujuan yang sama sudah tersedia.';
if($errors===[]){$params=['service_id'=>$data['shipping_service_id'],'province'=>$data['province'],'city'=>$data['city'],'district'=>$data['district']?:null,'first'=>$data['first_kg_price'],'next'=>$data['next_kg_price'],'cod'=>$data['supports_cod'],'cod_check'=>$data['supports_cod_check'],'cod_fee'=>$data['cod_fee'],'active'=>$data['is_active']];if($isEdit){$params['id']=$id;$st=$pdo->prepare('UPDATE shipping_rates SET shipping_service_id=:service_id,province=:province,city=:city,district=:district,first_kg_price=:first,next_kg_price=:next,supports_cod=:cod,supports_cod_check=:cod_check,cod_fee=:cod_fee,is_active=:active,updated_at=NOW() WHERE id=:id');$st->execute($params);}else{$st=$pdo->prepare('INSERT INTO shipping_rates(shipping_service_id,province,city,district,first_kg_price,next_kg_price,supports_cod,supports_cod_check,cod_fee,is_active) VALUES(:service_id,:province,:city,:district,:first,:next,:cod,:cod_check,:cod_fee,:active)');$st->execute($params);}log_admin_activity($pdo,'shipping_rate_save','Menyimpan tarif pengiriman '.$data['city'].', '.$data['province']);flash('success','Tarif pengiriman berhasil disimpan.');redirect('shipping_rates.php?service_id='.$data['shipping_service_id']);}}
$pageTitle=$isEdit?'Edit Tarif':'Tambah Tarif';$activeMenu='shipping';require __DIR__.'/includes/admin_header.php';
?>
<div class="admin-page-head"><div><h1><?=e($pageTitle)?></h1><p>Tarif pertama berlaku untuk 1 kg pertama, lalu tarif berikutnya per kg tambahan.</p></div><a class="admin-button admin-button-secondary" href="shipping_rates.php">← Kembali</a></div><?php if($errors):?><ul class="admin-error-list"><?php foreach($errors as $er):?><li><?=e($er)?></li><?php endforeach;?></ul><?php endif;?>
<form class="admin-card admin-form-stack" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><?php if($isEdit):?><input type="hidden" name="rate_id" value="<?=(int)$id?>"><?php endif;?><div class="admin-form-grid"><label class="admin-field"><span>Layanan pengiriman</span><select class="admin-select" name="shipping_service_id" required><option value="">Pilih layanan</option><?php foreach($services as $s):?><option value="<?=(int)$s['id']?>" <?=(int)$data['shipping_service_id']===(int)$s['id']?'selected':''?>><?=e((string)$s['courier_name'])?> — <?=e((string)$s['service_code'])?> <?=e((string)$s['service_name'])?></option><?php endforeach;?></select></label><label class="admin-field"><span>Provinsi</span><input class="admin-input" name="province" maxlength="100" value="<?=e((string)$data['province'])?>" required></label><label class="admin-field"><span>Kota/Kabupaten</span><input class="admin-input" name="city" maxlength="100" value="<?=e((string)$data['city'])?>" required></label><label class="admin-field"><span>Kecamatan (opsional)</span><input class="admin-input" name="district" maxlength="100" value="<?=e((string)$data['district'])?>" placeholder="Kosong = semua kecamatan"></label><label class="admin-field"><span>Tarif 1 kg pertama</span><input class="admin-input" type="number" min="0" step="100" name="first_kg_price" value="<?=e((string)$data['first_kg_price'])?>" required></label><label class="admin-field"><span>Tarif per kg berikutnya</span><input class="admin-input" type="number" min="0" step="100" name="next_kg_price" value="<?=e((string)$data['next_kg_price'])?>" required></label><label class="admin-field"><span>Biaya COD</span><input class="admin-input" type="number" min="0" step="100" name="cod_fee" value="<?=e((string)$data['cod_fee'])?>"></label></div><div class="admin-checkbox-grid"><label class="admin-check"><input type="checkbox" name="supports_cod" <?=(int)$data['supports_cod']===1?'checked':''?>><span>Tersedia untuk COD</span></label><label class="admin-check"><input type="checkbox" name="supports_cod_check" <?=(int)$data['supports_cod_check']===1?'checked':''?>><span>Tersedia untuk COD Cek Dulu</span></label><label class="admin-check"><input type="checkbox" name="is_active" <?=(int)$data['is_active']===1?'checked':''?>><span>Tarif aktif</span></label></div><div class="admin-form-actions"><button class="admin-button admin-button-primary" type="submit">Simpan Tarif</button></div></form>
<?php require __DIR__.'/includes/admin_footer.php';?>
